language: node_js
node_js:
    - "6"
script:
    - |
        cat <<EOF > src/secrets.js
        export const clientId = 'placeholder';
        export const clientSecret = 'placeholder';
        export const LISH_ROOT = 'wss://lish.alpha.linode.com';
        EOF
    - npm test
    - node ./node_modules/lcov-filter/index.js ./coverage/lcov.info styleguide | ./node_modules/.bin/coveralls
    - npm run lint
